apiVersion: v1
kind: ServiceAccount
metadata:
  name: egress-cilium-node-operator-acc
  namespace: operator-egress-cilium-node

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: egress-cilium-node-operator
rules:
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list", "patch"]
- apiGroups: ["cilium.io"]
  resources: ["ciliumegressgatewaypolicies"]
  verbs: ["get", "watch", "list", "patch", "create"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: egress-cilium-node-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: egress-cilium-node-operator
subjects:
  - kind: ServiceAccount
    name: egress-cilium-node-operator-acc
    namespace: operator-egress-cilium-node

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: egress-cilium-node-operator
  namespace: operator-egress-cilium-node
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: egress-cilium-node-operator
  template:
    metadata:
      labels:
        app: egress-cilium-node-operator
    spec:
      containers:
        - name: shell-operator
          image: filigran/egress-cilium-node-operator:latest
          imagePullPolicy: Always
      serviceAccountName: egress-cilium-node-operator-acc
      imagePullSecrets:
        - name: filigrandocker
